# Generated by Django 3.2.12 on 2024-10-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='team_leader_id_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_submissions', to='organization.team'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='attach_feed_FK',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='assignment.attachment'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='submission_id_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments_related', to='assignment.submission'),
        ),
        migrations.AddField(
            model_name='assignmentsubtask',
            name='ass_to_subtask_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_subtasks', to='assignment.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubtask',
            name='assign_subtask_reviewer_FK',
            field=models.ManyToManyField(related_name='assignment_subtasks_reviewer', to='assignment.Assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubtask',
            name='assign_subtask_status_FK',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_subtasks', to='assignment.submission'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assign_reviewer_FK',
            field=models.ManyToManyField(blank=True, related_name='reviewed_assignments', to='organization.OrgMember'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_teams_FK',
            field=models.ManyToManyField(related_name='assignments', to='organization.Team'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_assign_creator_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_assignments', to='organization.orgmember'),
        ),
    ]
